name: Publish flowchart

on:
  workflow_run:
    workflows:
    - Release
    types:
    - completed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:

    - name: Fetch latest flowchart
      run: |
        cp https://github.com/nicholasdille/freisitz/releases/latest/download/freisitz.svg .

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: .

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
