name: Release

on:
  push:
    tags:
    - 'v*'

jobs:

  prepare:
    name: Prepare
    runs-on: ubuntu-22.04
    outputs:
      tag: ${{ steps.get_version.outputs.tag }}
    steps:

    - name: printenv
      run: |
        printenv | sort

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get version
      id: get_version
      run: |
        TAG="${GITHUB_REF#refs/tags/}"
        echo "tag=${TAG}" >>"${GITHUB_OUTPUT}"

  release:
    runs-on: ubuntu-22.04
    needs: prepare
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get -y install graphviz

    - name: Build flowchart
      run: |
        make freisitz.svg
    
    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.BOT_GITHUB_TOKEN }}
        allowUpdates: true
        name: "Version ${{ github.ref }}"
        tag: ${{ github.ref }}
        draft: false
        replacesArtifacts: true
        artifacts: "freisitz.svg"